FROM httpd:latest
COPY ./ethersapp /usr/local/apache2/htdocs/ethersapp
COPY ./etherwallet /usr/local/apache2/htdocs/etherwallet
COPY ./etherchain-light-master /usr/local/apache2/htdocs/etherchain

EXPOSE 80
